### PR TITLE
fix: verify the changelog before it is commited

### LINKED ISSUE #3: Exit with non-zero status if the job fails
It would be good to have an extra check in case the job fails. Here's some ideas for things we can check:

 - We should **not** have lots (> 10) of deletions
 - The changelog should **not** say "There is no job for .... Make a POST first." (... is the repo name)
 - The changelog should **not** be one line long after running

All these checks need to run **before** committing, and **should revert the change** (`git checkout -- .`) if they're not passed.

The script should exit with a good error message and a non-zero status.

### PR DESCRIPTION
**Pull request by freitagbr**
Fixes #3 

Verify the following about the changelog before it is commited:

* It is not one line long.
* It does not contain more than 10 deletions.
* It does not contain the error message "There is no job for ...
  Make a POST first."

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -10,9 +10,39 @@ function parseGitUri(uri) {
...
+  var deletions = 0;
+  var containsErrorMessage = false;
+  lines.filter(function (line) {
+    if (/^-/.test(line)) deletions++;
+    if (line.indexOf('Make a POST first') >= 0) containsErrorMessage = true;
+  });
+  if (isOneLine) {
+    revertChanges();
+    console.error('Changelog diff should be more than 1 line long');
+    process.exit(3);
```
Comment (nfischer) [inline index.js]: Exceptions might be a cleaner way of doing this. Same for the other exits below.

File: index.js [hunk 2]
```diff
@@ -41,6 +71,8 @@ function run() {
   });
 
   if (changelog_was_updated) {
+    echo('...verifying changelog');
+    verifyChangelog();
```
Comment (nfischer) [inline index.js]: Wrap this in a try-catch. If it throws, you can call `revertChanges()` and output something to indicate what happens. It's reasonable to use one exit code to cover all these cases.

Alternatively, we could leave the changes and just not commit them, in which case we should direct the user to manually verify the changes, and run `git checkout -- CHANGELOG.md` if they want to revert.

File: index.js [hunk 3]
```diff
@@ -10,9 +10,39 @@ function parseGitUri(uri) {
     uri.match(/git@github.com:(.*)\/(.*)\.git/);
 }
 
+function verifyChangelog() {
+  var changelog = exec('git diff HEAD~1');
```
Comment (nfischer) [inline index.js]: I think this should be HEAD, since we haven't committed yet. Also, make sure you're only checking `CHANGELOG.md`.

File: index.js [hunk 4]
```diff
@@ -10,9 +10,39 @@ function parseGitUri(uri) {
...
+  var lines = changelog.split('\n');
+  var isOneLine = (lines.length === 1);
```
Comment (nfischer) [inline index.js]: Can you double check this line? A one-line file would probably return 2 here. A typical one-line file would look something like `This is the only line\n`, which splits as `[ 'This is the only line', '']`.

Maybe we can pop off `lines[lines.length-1]` if it's empty.

File: index.js [hunk 5]
```diff
@@ -10,9 +10,39 @@ function parseGitUri(uri) {
...
+  var deletions = 0;
+  var containsErrorMessage = false;
+  lines.filter(function (line) {
```
Comment (nfischer) [inline index.js]: I think `forEach` is what you're looking for?

It might be cleaner to filter this and then let `deletions = lines.filter(...).length`.

File: index.js [hunk 6]
```diff
@@ -10,9 +10,39 @@ function parseGitUri(uri) {
...
+    if (/^-/.test(line)) deletions++;
+    if (line.indexOf('Make a POST first') >= 0) containsErrorMessage = true;
+  });
+  if (isOneLine) {
+    revertChanges();
+    console.error('Changelog diff should be more than 1 line long');
+    process.exit(3);
+  }
+  if (deletions > 10) {
```
Comment (nfischer) [inline index.js]: Is 10 the best number for this? I just suggested an arbitrary value, but we may be able to narrow this down to a better number. Also, please add a comment explaining the rational behind this number (if it's totally arbitrary, you can just say so).

File: index.js (hunk 4 above)
Comment (nfischer) [reply index.js]: Also, `isOneLine` should check the length of `CHANGELOG.md`, not the diff's length.

**Review by nfischer — CHANGES_REQUESTED** [review]
I left some comments that need to be verified before committing. You can just sym-link your local shelljs-changelog into something like the shelljs or shx repo's node_modules to manually test.

File: index.js (hunk 3 above)
Comment (freitagbr) [reply index.js]: Right, the command should be `git diff HEAD CHANGELOG.md`.

File: index.js (hunk 4 above)
Comment (freitagbr) [reply index.js]: Right, that makes more sense.

File: index.js (hunk 6 above)
Comment (freitagbr) [reply index.js]: Well, should there be any deletions at all? It seems like the if there would be a difference in the changelog, it would only be in the form of additions (unless I am missing something).

File: index.js (hunk 2 above)
Comment (freitagbr) [reply index.js]: I don't necessarily like the idea of a script like this committing for me, BUT, it is nice to have the commit message automatically generated. So I think I will implement the try-catch.

File: index.js (hunk 6 above)
Comment (nfischer) [reply index.js]: It changes some lines sometimes, which show up as deletions and insertions. This should only be 1-2 lines I think.

Comment (freitagbr) [reply index.js]: I checked the history to see how many deletions there are typically when the changelog is updated:
```
$ commits=`git log --oneline --before="6 days ago" | grep "docs(changelog)" | grep -Po '^\w+'`
$ for c in $commits; do echo $c; git diff $c~1..$c | grep '^-[^-]'; echo; done
2089d3e
-[Full Changelog](https://github.com/shelljs/shelljs/compare/v0.7.4...HEAD)

280c7fc

3986d61

e24b675
-## [Unreleased](https://github.com/shelljs/shelljs/tree/HEAD)
-[Full Changelog](https://github.com/shelljs/shelljs/compare/v0.7.2...HEAD)

cec859e

413bc79
-## [Unreleased](https://github.com/shelljs/shelljs/tree/HEAD)
-[Full Changelog](https://github.com/shelljs/shelljs/compare/v0.7.0...HEAD)

430042f

```
It looks like there should be no more that 2 deletions, so I think that 2 should be the limit.

Comment (nfischer) [reply index.js]: Ok. If 2 is too strict, we can increase this later. @freitagbr can you move the number into a variable at the top and add an explanatory comment (briefly explain which two lines typically get changed).

File: index.js [hunk 7]
```diff
@@ -6,6 +6,11 @@ require('shelljs/global');
 // Commits the changelog if it updated
 // Does not push commit
 
+// The maximum number of deletions for updating the changelog should
+// be 2 lines. Typically, the "Unreleased" and "Full Changelog" links
+// are changed because the version increases.
+var maxDeletions = 2;
```
Comment (nfischer) [inline index.js]: Please capitalize the constant

File: index.js [hunk 8]
```diff
@@ -1,18 +1,51 @@
...
+  if (changelog[changelog.length - 1] === '') changelog.pop();
+  var isOneLine = (changelog.length === 1);
+  var deletions = diff.filter(/^-/.test).length;
+  var containsError = false;
+  diff.forEach(function (line) {
+    if (line.indexOf('Make a POST first') >= 0) containsError = true;
+  });
+  assert(
+    changelog.length > 1,
+    'Changelog diff should be more than 1 line long'
```
Comment (nfischer) [inline index.js]: Change this to something like "Changelog was reduced to one line, this is probably an error..."

File: index.js [hunk 9]
```diff
@@ -1,18 +1,51 @@
...
+  );
+  assert(
+    deletions < MAX_DELETIONS,
+    'Too many deletions (-' + deletions + '), verify that the changes to CHANGELOG.md are correct'
```
Comment (nfischer) [inline index.js]: Since we're reverting anyway, it doesn't make sense to ask for manual verification. So we can either change this part of the message, or just not revert changes and instead display the command for a manual revert.

File: index.js [hunk 10]
```diff
@@ -1,18 +1,51 @@
...
 require('shelljs/global');
 
 // Creates a changelog for the current build and puts it in the root
 // Commits the changelog if it updated
 // Does not push commit
 
+// The maximum number of deletions for updating the changelog should
+// be 2 lines. Typically, the "Unreleased" and "Full Changelog" links
+// are changed because the version increases.
+var MAX_DELETIONS = 2;
```
Comment (nfischer) [inline index.js]: Let's increase this a little bit in case someone changes the name of a pull request or Github issue. Maybe 4 or 5 would be ok?

**Review by nfischer — CHANGES_REQUESTED** [review]
Assuming you've manually tested, this LGTM once my nits are addressed.

File: index.js (hunk 10 above)
Comment (freitagbr) [reply index.js]: 5 ought to be a good limit.

File: index.js (hunk 9 above)
Comment (freitagbr) [reply index.js]: I think I would prefer the changelog were automatically reverted, but in special circumstances we might want to increase the `MAX_DELETIONS` limit. Perhaps this should be configurable from the command line:
```
$ shelljs-changelog 10
# or
$ shelljs-changelog -d 10
# or
$ shelljs-changelog --max-deletions 10
```

Comment (nfischer) [reply index.js]: I think it'd be easier to have a `--force` that skips validation. It's up to the user to manually validate the last commit before pushing.

Comment (freitagbr) [reply index.js]: That's a better idea, I'll add that.

Comment (nfischer) [reply index.js]: LGTM once `--force` is added. Parsing with minimist is the most straightforward way to go. Either add a bit about `--force` in the error message or add it to the docs in the README.

File: index.js [hunk 11]
```diff
@@ -31,13 +35,16 @@ function verifyChangelog() {
...
   );
   assert(
-    deletions < MAX_DELETIONS,
-    'Too many deletions (-' + deletions + '), this is probably an error.'
-  );
-  assert(
     !containsError,
     'Changelog contains an error message.'
   );
+  if (!force) {
```
Comment (nfischer) [inline index.js]: @freitagbr Let's just skip all verification with `--force`. Ideally we'll never need `--force`, but just in case we do it'll be more flexible this way

**Review by nfischer — APPROVED** [review]
FFTM
